name: heimdall
description: A Flutter App for getting the statistical information of employee as per week.

publish_to: "none" # remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # for displaying bar charts
  fl_chart: ^0.55.0

  # for state management
  flutter_bloc: ^8.0.1

  # for opening links provided in chart details
  url_launcher: ^6.1.4

   # for implemeting login with Google
  google_sign_in: ^5.4.0

  # for calling api
  http: ^0.13.4

  # for storing environment variables
  flutter_dotenv: ^5.0.2

  # for intercepting http requests
  http_interceptor: ^1.0.2
  dio: ^4.0.6

  # for using expandable widget for filters
  expandable: ^5.0.1

  # added to store token in storage for maintaining session
  shared_preferences: ^2.0.15

  # added to validate the jwt tokens by checking their expiry date
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# the following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

